apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: changeme
    workspace: .
    docker:
      buildArgs:
        APP_NAME: victory
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: ox-dev-joel
