apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: victory
    workspace: .
    docker:
      buildArgs:
        APP_NAME: victory
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: ox-dev-joel
