apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: gcr.io/ox-dev-joel/victory
    workspace: .
    docker:
      buildArgs:
        APP_NAME: victory
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: ox-dev-joel
